import { useEffect, useMemo, useState } from "react";

const seedDashboard = {
  meta: { account_label: "FUTUINC · US · 实盘只读", account_mask: "•• 9612", synced_at: "2026-09-16 10:24:18", source: "演示数据", opend_status: "未连接" },
  metrics: { realized_gross: 12842.5, realized_net: 12491.36, period_cashflow: 8720.4, closed_cycles: 24, win_rate: 87.5, unrealized: -1846.2, premium_open: 9348 },
  expiry_buckets: [{ label: "2026-09", amount: 3420 }, { label: "2026-10", amount: 2360 }, { label: "2026-11", amount: 1418 }, { label: "2026-12", amount: 1250 }, { label: "2027-01", amount: 900 }],
  alerts: { expiring: 3, losing: 2, reconciliation: 0 },
  symbols: [
    { symbol: "TSLA", closed: 8, realized: 5260, open: 2, buyback: 2620, unrealized: -940, premium: 3480, win_rate: 87.5 },
    { symbol: "NVDA", closed: 6, realized: 3240, open: 3, buyback: 1480, unrealized: 610, premium: 2760, win_rate: 100 },
    { symbol: "GOOGL", closed: 5, realized: 2180, open: 2, buyback: 890, unrealized: -720, premium: 1870, win_rate: 80 },
    { symbol: "SKHY", closed: 5, realized: 1811.36, open: 2, buyback: 720, unrealized: -796.2, premium: 1238, win_rate: 80 },
  ],
  positions: [
    { id: 1, side: "Sell Put", symbol: "TSLA", expiry: "2026-09-18", option_type: "Put", strike: 410, opened: "2026-09-08", days_open: 8, quantity: 1, dte: 2, premium: 1420, mark: 20.8, unrealized: -660, return_rate: -46.5, status: "临近到期" },
    { id: 2, side: "Sell Call", symbol: "NVDA", expiry: "2026-10-16", option_type: "Call", strike: 210, opened: "2026-09-11", days_open: 5, quantity: 2, dte: 30, premium: 1760, mark: 5.75, unrealized: 610, return_rate: 34.7, status: "持有中" },
    { id: 3, side: "Sell Put", symbol: "GOOGL", expiry: "2026-10-16", option_type: "Put", strike: 225, opened: "2026-09-05", days_open: 11, quantity: 1, dte: 30, premium: 940, mark: 16.6, unrealized: -720, return_rate: -76.6, status: "浮亏" },
    { id: 4, side: "Sell Put", symbol: "SKHY", expiry: "2026-09-25", option_type: "Put", strike: 165, opened: "2026-09-12", days_open: 4, quantity: 1, dte: 9, premium: 1180, mark: 17.1, unrealized: -530, return_rate: -44.9, status: "持有中" },
  ],
  closed: [
    { id: 21, side: "Sell Put", symbol: "TSLA", expiry: "2026-09-11", strike: 390, quantity: 1, opened: "2026-09-03", closed: "2026-09-10", premium: 1170, buyback: 280, fees: 3.18, pnl: 886.82 },
    { id: 22, side: "Sell Call", symbol: "NVDA", expiry: "2026-09-11", strike: 205, quantity: 2, opened: "2026-09-04", closed: "2026-09-09", premium: 980, buyback: 310, fees: 5.22, pnl: 664.78 },
    { id: 23, side: "Sell Put", symbol: "GOOGL", expiry: "2026-09-11", strike: 220, quantity: 1, opened: "2026-09-02", closed: "2026-09-08", premium: 740, buyback: 925, fees: 3.05, pnl: -188.05 },
  ],
};

const emptyDashboard = { meta:{account_label:"账户尚未验证",account_mask:"••••",synced_at:"—",source:"尚无真实数据",opend_status:"未验证"}, metrics:{realized_gross:0,realized_net:0,period_cashflow:0,closed_cycles:0,win_rate:0,unrealized:0,premium_open:0}, expiry_buckets:[], alerts:{expiring:0,losing:0,reconciliation:0}, symbols:[], positions:[], closed:[] };

const money = (value) => { const n = Number(value || 0); return `${n < 0 ? "−" : ""}$${Math.abs(n).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; };
const Pill = ({ children, tone = "neutral" }) => <span className={`pill ${tone}`}>{children}</span>;
const dateKey = (value) => `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;
function rangeBounds(range, now = new Date()) { const today = new Date(now.getFullYear(), now.getMonth(), now.getDate()); if (range === "today") return { start:dateKey(today), end:dateKey(today) }; if (range === "week") { const first = new Date(today); first.setDate(today.getDate() - ((today.getDay()+6)%7)); return { start:dateKey(first), end:dateKey(today) }; } if (range === "last_month") { const first = new Date(today.getFullYear(),today.getMonth()-1,1), last = new Date(today.getFullYear(),today.getMonth(),0); return { start:dateKey(first), end:dateKey(last) }; } return { start:dateKey(new Date(today.getFullYear(),today.getMonth(),1)), end:dateKey(today) }; }
function scopedDashboard(dashboard, filters) { const matchesSymbol = row => !filters.symbol || row.symbol === filters.symbol; const closed = dashboard.closed.filter(row => matchesSymbol(row) && row.closed >= filters.start && row.closed <= filters.end); const positions = dashboard.positions.filter(matchesSymbol); const symbols = [...new Set([...closed,...positions].map(row => row.symbol))].sort().map(symbol => { const cp=closed.filter(row=>row.symbol===symbol), op=positions.filter(row=>row.symbol===symbol), realized=cp.reduce((sum,row)=>sum+Number(row.pnl||0),0), unrealized=op.reduce((sum,row)=>sum+Number(row.unrealized||0),0); return { symbol, closed:cp.length, realized, open:op.length, buyback:op.reduce((sum,row)=>sum+Number(row.mark||0)*100*Number(row.quantity||0),0), unrealized, premium:op.reduce((sum,row)=>sum+Number(row.premium||0),0), win_rate:cp.length?Math.round(cp.filter(row=>Number(row.pnl)>0).length/cp.length*1000)/10:0 }; }); const net=closed.reduce((sum,row)=>sum+Number(row.pnl||0),0), gross=closed.reduce((sum,row)=>sum+Number(row.gross_pnl ?? (Number(row.pnl||0)+Number(row.fees||0))),0), openPremium=positions.reduce((sum,row)=>sum+Number(row.premium||0),0), openUnrealized=positions.reduce((sum,row)=>sum+Number(row.unrealized||0),0), buckets={}; positions.forEach(row=>{ const key=row.expiry.slice(0,7); buckets[key]=(buckets[key]||0)+Number(row.premium||0); }); return {...dashboard, closed, positions, symbols, metrics:{...dashboard.metrics,realized_gross:gross,realized_net:net,period_cashflow:net,closed_cycles:closed.length,win_rate:closed.length?Math.round(closed.filter(row=>Number(row.pnl)>0).length/closed.length*1000)/10:0,unrealized:openUnrealized,premium_open:openPremium}, expiry_buckets:Object.entries(buckets).sort(([a],[b])=>a.localeCompare(b)).slice(0,5).map(([label,amount])=>({label,amount})), alerts:{...dashboard.alerts,expiring:positions.filter(row=>row.dte>=0&&row.dte<=7).length,losing:positions.filter(row=>Number(row.unrealized)<0).length}}; }

function Metric({ label, value, note, tone = "normal" }) { return <div className="metric"><div className="metric-label">{label}</div><div className={`metric-value ${tone}`}>{value}</div><div className="metric-note">{note}</div></div>; }

function AppHeader({ dashboard, onSync, syncing }) { return <><header className="topbar"><div><div className="eyebrow">OPTIONS / PREMIUM LEDGER</div><h1>期权卖方算账神器</h1></div><div className="account-block"><strong>{dashboard.meta.account_label}</strong><span>统一账号尾号 {dashboard.meta.account_mask}</span></div></header><section className="sync-strip page-width"><div><div className="sync-title"><span className={`status-dot ${dashboard.meta.opend_status === "已连接" ? "online" : ""}`} /> 数据同步 · 富途 OpenD</div><div className="sync-meta">最近同步 {dashboard.meta.synced_at} · 来源 {dashboard.meta.source} · {dashboard.meta.opend_status}</div></div><button className="primary" onClick={onSync} disabled={syncing}>{syncing ? "正在同步…" : "立即同步"}</button></section></>; }

function Summary({ dashboard, filters, setFilters }) { const m = dashboard.metrics; return <section className="panel summary-panel"><div className="section-heading split"><div><h2>收益统计</h2><p>仅统计卖空期权及对应买回平仓；正股、买方期权与未配对成交不纳入。</p></div><span className="subtle">按平仓日归属 · FIFO 配对</span></div><div className="filter-row"><div className="quick-range">{[["today","今天"],["week","本周"],["month","本月"],["last_month","上月"]].map(([key,label]) => <button key={key} className={filters.range === key ? "active" : ""} onClick={() => setFilters({ ...filters, range:key, ...rangeBounds(key) })}>{label}</button>)}</div><label>起始 <input type="date" value={filters.start} onChange={(e) => setFilters({ ...filters, start: e.target.value, range: "custom" })} /></label><label>结束 <input type="date" value={filters.end} onChange={(e) => setFilters({ ...filters, end: e.target.value, range: "custom" })} /></label><select value={filters.symbol} onChange={(e) => setFilters({ ...filters, symbol: e.target.value })}><option value="">全部标的</option>{dashboard.symbols.map(s => <option key={s.symbol}>{s.symbol}</option>)}</select><button className="secondary" type="button">已筛选</button></div><div className="metrics-grid"><Metric label="已实现毛盈利 · USD" value={money(m.realized_gross)} note="平仓成交价差 × 乘数" /><Metric label="已实现净盈利 · USD" value={money(m.realized_net)} note="已扣除已知交易费用" /><Metric label="期间净现金流 · USD" value={money(m.period_cashflow)} note="仅本筛选期间已平仓轮次" /><Metric label="已结束轮次 / 胜率" value={`${m.closed_cycles} / ${m.win_rate}%`} note="仅完整平仓轮次" /><Metric label="当前持仓浮盈 · USD" value={money(m.unrealized)} note="当前快照；不按平仓日过滤" tone={m.unrealized < 0 ? "loss" : "gain"} /></div><div className="expiry-row"><div className="expiry-total"><span>待落袋权利金</span><strong>{money(m.premium_open)}</strong></div>{dashboard.expiry_buckets.map(b => <div className="expiry-item" key={b.label}><span>{b.label}</span><strong>{money(b.amount)}</strong></div>)}</div></section>; }

function Alerts({ alerts }) { return <section className="alerts-grid"><div className="alert-card warn"><div><span>临近到期</span><b>≤ 7 天</b></div><strong>{alerts.expiring} 轮</strong><p>建议优先检查滚仓或买回条件。</p></div><div className="alert-card danger"><div><span>当前浮亏</span><b>未平仓快照</b></div><strong>{alerts.losing} 轮</strong><p>仅显示期权卖方头寸的估算浮盈亏。</p></div><div className="alert-card ok"><div><span>待核对</span><b>数据覆盖</b></div><strong>{alerts.reconciliation} 轮</strong><p>{alerts.reconciliation ? "存在无法与卖出开仓配对的买入。" : "所有期权成交均已完成配对。"}</p></div></section>; }

function StockHoldings({ rows, updatedAt }) { return <section className="panel compact-panel stock-panel"><div className="section-heading split"><div><h2>正股持仓表</h2><p>每周快速检查：整行浅绿表示至少已卖一项；整行浅红表示两项均未卖。每项文字独立以绿、红区分。</p></div><span className="subtle">{updatedAt ? `正股快照 ${updatedAt}` : "尚未同步正股快照"}</span></div>{rows.length ? <div className="table-wrap"><table className="stock-table"><thead><tr><th>正股</th><th>Covered Call</th><th>Sell Put</th></tr></thead><tbody>{rows.map(row => { const hasCall = Number(row.covered_calls) > 0; const hasPut = Number(row.sell_puts) > 0; return <tr key={row.code} className={`holding-row ${hasCall || hasPut ? "operated" : "untouched"}`}><td><strong>{row.symbol}</strong><small>{row.stock_name}</small></td><td><span className={hasCall ? "option-done" : "option-pending"}>{hasCall ? "已卖" : "未卖"}</span></td><td><span className={hasPut ? "option-done" : "option-pending"}>{hasPut ? "已卖" : "未卖"}</span></td></tr>; })}</tbody></table></div> : <div className="empty">尚无已同步的真实正股持仓。请确认 OpenD 已启动后点击“立即同步”。</div>}</section>; }

function SymbolTable({ rows }) { return <section className="panel compact-panel"><div className="section-heading"><h2>标的期权聚合</h2><p>已结束为完整平仓轮次；持有中仅统计未平仓卖方合约。</p></div><div className="table-wrap"><table><thead><tr><th>标的</th><th>已结束</th><th>已实现净盈利</th><th>持有中</th><th>当前买回估值</th><th>当前浮盈亏</th><th>权利金流入</th><th>胜率</th></tr></thead><tbody><tr className="total-row"><td>合计</td><td>{rows.reduce((a,r)=>a+r.closed,0)} 轮</td><td>{money(rows.reduce((a,r)=>a+r.realized,0))}</td><td>{rows.reduce((a,r)=>a+r.open,0)} 轮</td><td>{money(rows.reduce((a,r)=>a+r.buyback,0))}</td><td>{money(rows.reduce((a,r)=>a+r.unrealized,0))}</td><td>{money(rows.reduce((a,r)=>a+r.premium,0))}</td><td>—</td></tr>{rows.map(r => <tr key={r.symbol}><td><strong>{r.symbol}</strong></td><td>{r.closed} 轮</td><td className="gain-text">{money(r.realized)}</td><td>{r.open} 轮</td><td>{money(r.buyback)}</td><td className={r.unrealized < 0 ? "loss-text" : "gain-text"}>{money(r.unrealized)}</td><td>{money(r.premium)}</td><td>{r.win_rate}%</td></tr>)}</tbody></table></div></section>; }

function ProfitBars({ rows }) { const max = Math.max(...rows.map(r => Math.abs(r.realized)), 1); const total = rows.reduce((sum, row) => sum + Number(row.realized || 0), 0); const best = rows.reduce((leader, row) => !leader || row.realized > leader.realized ? row : leader, null); const lossCount = rows.filter(row => Number(row.realized) < 0).length; return <section className="panel bars-panel"><div className="section-heading split"><div><h2>本期已实现净盈利 · 标的对比</h2><p>绿色为盈利，红色为亏损；按平仓日归属。</p></div><span className="subtle">USD</span></div><div className="bars">{rows.map(r => <div className="bar-row" key={r.symbol}><strong>{r.symbol}</strong><div className="track"><div className={`bar ${r.realized < 0 ? "negative" : ""}`} style={{width:`${Math.max(2, Math.abs(r.realized)/max*100)}%`}} /></div><span className={r.realized < 0 ? "loss-text" : "gain-text"}>{money(r.realized)}</span></div>)}</div><div className="profit-summary"><div><span>本期净盈利</span><strong className={total < 0 ? "loss-text" : "gain-text"}>{money(total)}</strong></div><div><span>表现最佳</span><strong>{best?.symbol || "—"}</strong><small>{best ? money(best.realized) : "—"}</small></div><div><span>亏损标的</span><strong className={lossCount ? "loss-text" : "gain-text"}>{lossCount} 个</strong><small>{lossCount ? "建议复盘" : "暂无"}</small></div></div></section>; }

function Ledger({ dashboard }) { const [tab, setTab] = useState("open"); const [query, setQuery] = useState(""); const rows = tab === "open" ? dashboard.positions : dashboard.closed; const shown = rows.filter(r => !query || `${r.symbol} ${r.expiry} ${r.side}`.toLowerCase().includes(query.toLowerCase())); return <section className="panel ledger-panel"><nav className="tabs"><button className={tab === "open" ? "active" : ""} onClick={() => setTab("open")}>当前持仓 <span>{dashboard.positions.length}</span></button><button className={tab === "closed" ? "active" : ""} onClick={() => setTab("closed")}>已平仓轮次 <span>{dashboard.closed.length}</span></button></nav><div className="ledger-tools"><input placeholder="搜索标的、合约或方向" value={query} onChange={e=>setQuery(e.target.value)} /><select><option>全部 Call / Put</option><option>仅 Put</option><option>仅 Call</option></select><button className="secondary" onClick={() => setQuery("")}>重置</button><button className="ghost" onClick={() => downloadCsv(shown)}>导出 CSV</button></div><div className="section-heading split"><div><h2>{tab === "open" ? "卖方持仓明细" : "已平仓收益明细"}</h2><p>{tab === "open" ? "按最新可得期权行情估值；没有行情时明确标记。" : "每一行是一段由卖出开仓到买回平仓的 FIFO 配对。"}</p></div><span className="subtle">{shown.length} 条记录</span></div><div className="trade-list">{shown.map(row => tab === "open" ? <OpenTrade key={row.id} row={row} /> : <ClosedTrade key={row.id} row={row} />)}{!shown.length && <div className="empty">没有符合当前筛选条件的记录</div>}</div></section>; }

function OpenTrade({ row }) { const losing = row.unrealized < 0; const breach = Number.isFinite(Number(row.breach_probability)) ? `${Number(row.breach_probability).toFixed(1)}%` : "—"; return <article className={`trade-card ${losing ? "losing" : ""}`}><div className="trade-strategy"><strong>{row.side}</strong><span>持有中</span></div><div><Pill tone="green">{row.symbol}</Pill><h3>{row.expiry} · {row.option_type} · ${row.strike.toFixed(2)}</h3><p>开仓 {row.opened} · 持有 {row.days_open} 天</p></div><div><span className="cell-label">持有数量</span><strong>{row.quantity} 张</strong></div><div><span className="cell-label">开仓权利金</span><strong>{money(row.premium)}</strong></div><div><span className="cell-label">当前买回估值</span><strong>{money(row.mark * 100 * row.quantity)}</strong></div><div><span className="cell-label">到期击穿概率</span><strong className={breach === "—" ? "pending-value" : ""}>{breach}</strong><small className="probability-note">{row.breach_note || "尚未同步风险快照"}</small></div><div className={`pnl-box ${losing ? "negative" : "positive"}`}><span>当前浮盈亏</span><strong>{money(row.unrealized)}</strong><small>收益率 {row.return_rate}%</small></div><div className="trade-status"><Pill tone={row.dte <= 7 ? "amber" : "neutral"}>{row.status}</Pill><strong>到期 {row.dte} 天</strong></div></article>; }

function ClosedTrade({ row }) { return <article className={`trade-card closed ${row.pnl < 0 ? "losing" : ""}`}><div className="trade-strategy"><strong>{row.side}</strong><span>已平仓</span></div><div><Pill tone="green">{row.symbol}</Pill><h3>{row.expiry} · ${row.strike.toFixed(2)}</h3><p>{row.opened} → {row.closed}</p></div><div><span className="cell-label">权利金流入</span><strong>{money(row.premium)}</strong></div><div><span className="cell-label">买回 / 费用</span><strong>{money(row.buyback)} / {money(row.fees)}</strong></div><div className={`pnl-box ${row.pnl < 0 ? "negative" : "positive"}`}><span>已实现净盈利</span><strong>{money(row.pnl)}</strong></div><div className="trade-status"><Pill tone={row.pnl < 0 ? "red" : "green"}>{row.pnl < 0 ? "亏损" : "盈利"}</Pill><strong>{row.quantity} 张</strong></div></article>; }

function Settings({ open, onClose, settings, setSettings }) { if (!open) return null; return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow green">DATA CONNECTOR</div><h2>富途 OpenD 连接</h2></div><button className="close" onClick={onClose}>关闭</button></div><p className="modal-copy">系统只读取成交、订单费用和期权行情，不保存交易密码，也不调用下单接口。</p><div className="form-grid"><label>OpenD 主机<input value={settings.host} onChange={e=>setSettings({...settings,host:e.target.value})} /></label><label>端口<input type="number" value={settings.port} onChange={e=>setSettings({...settings,port:e.target.value})} /></label><label>富途业务账户 ID / 尾号<input placeholder="请输入你的账户尾号" value={settings.accountId} onChange={e=>setSettings({...settings,accountId:e.target.value})} /></label><label>券商<select value={settings.broker} onChange={e=>setSettings({...settings,broker:e.target.value})}><option value="FUTUINC">FUTUINC / Moomoo US</option><option value="FUTUSECURITIES">FUTUSECURITIES / 富途证券</option></select></label><label className="full">首次同步起始日期<input type="date" value={settings.since} onChange={e=>setSettings({...settings, since:e.target.value})} /></label></div><div className="notice"><strong>账户校验</strong><span>系统只会读取 OpenD 当前登录且授权的同一账户；如果尾号无法匹配，会停止同步并提示你切换 OpenD 登录账户，绝不自动改用其他账户。</span></div><div className="modal-actions"><button className="secondary" onClick={onClose}>取消</button><button className="primary" onClick={onClose}>保存配置</button></div></section></div>; }

function downloadCsv(rows) { if (!rows.length) return; const headers = Object.keys(rows[0]); const csv = [headers.join(","), ...rows.map(row => headers.map(h => JSON.stringify(row[h] ?? "")).join(","))].join("\n"); const url = URL.createObjectURL(new Blob(["\ufeff", csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "option-ledger.csv"; a.click(); URL.revokeObjectURL(url); }

async function parseApiResponse(response) { const raw = await response.text(); if (!raw.trim()) throw new Error("同步服务没有响应，请确认本地 API 已启动"); try { return JSON.parse(raw); } catch { throw new Error(`同步服务返回了无法识别的内容（HTTP ${response.status}）`); } }

export function App() { const savedSettings = (() => { try { return JSON.parse(localStorage.getItem("option-ledger-settings")) } catch { return null } })(); const defaults = { host: "127.0.0.1", port: 11111, accountId: "", broker: "FUTUSECURITIES", since: "2025-01-01" }; const [dashboard, setDashboard] = useState(emptyDashboard); const [syncing, setSyncing] = useState(false); const [message, setMessage] = useState("尚无已验证的真实数据。请连接本机 OpenD 后同步成交。"); const [settingsOpen, setSettingsOpen] = useState(false); const [settings, setSettings] = useState({...defaults, ...savedSettings, accountId: savedSettings?.accountId || defaults.accountId}); const [filters, setFilters] = useState({ range: "month", ...rangeBounds("month"), symbol: "" }); useEffect(() => { fetch("/api/dashboard").then(r => r.ok ? r.json() : Promise.reject()).then(data => { if (data?.meta?.opend_status === "已连接") { setDashboard(data); setMessage("已载入已验证的真实成交数据。"); } }).catch(() => {}); }, []); useEffect(() => { localStorage.setItem("option-ledger-settings", JSON.stringify(settings)); }, [settings]); const scoped = useMemo(() => scopedDashboard(dashboard, filters), [dashboard, filters]); async function sync() { setSyncing(true); setMessage("正在连接 OpenD 并读取成交…"); try { const res = await fetch("/api/sync", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const data = await parseApiResponse(res); if (!res.ok) throw new Error(data.error || `同步失败（HTTP ${res.status}）`); setDashboard(data.dashboard); setMessage(`已同步真实数据：新增 ${data.inserted} 笔成交，更新 ${data.fees_updated} 笔费用。`); } catch (err) { setDashboard(emptyDashboard); setMessage(`${err.message}。未显示任何未验证或演示数据。`); } finally { setSyncing(false); } } return <div className="app-shell"><AppHeader dashboard={scoped} onSync={sync} syncing={syncing} /><main className="page-width content"><div className="banner"><span>{message}</span><button onClick={()=>setSettingsOpen(true)}>连接设置</button></div><Summary dashboard={scoped} filters={filters} setFilters={setFilters} /><div className="daily-note">每日优先检查 · 所有数字均为当前快照，不构成交易建议</div><Alerts alerts={scoped.alerts} /><div className="holdings-insights"><StockHoldings rows={dashboard.stock_holdings || []} updatedAt={dashboard.holdings_updated_at} /><ProfitBars rows={scoped.symbols} /></div><SymbolTable rows={scoped.symbols} /><Ledger dashboard={scoped} /></main><footer><span>Option Premium Ledger</span><span>只读 · 本地优先 · FIFO</span></footer><Settings open={settingsOpen} onClose={()=>setSettingsOpen(false)} settings={settings} setSettings={setSettings} /></div>; }
